### PR TITLE
[CUMULUS-2479] /version

### PR DESCRIPTION
**Pull request by dopeters**
**Summary:** Summary of changes

Addresses [CUMULUS-2479: Implement /version](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2479)

## Changes

* Used existing /version implementation for distribution API

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [x] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

**Review by jennyhliu — APPROVED** [review]
LGTM.  Need to update https://nasa.github.io/cumulus-distribution-api/ though.

**Comment by dopeters** [comment]
> LGTM. Need to update [nasa.github.io/cumulus-distribution-api](https://nasa.github.io/cumulus-distribution-api/) though.

Ah right. Will link the PR here once it's ready

**Comment by Jkovarik** [comment]
This looks like it's approved, does it still need a review?

**Comment by dopeters** [comment]
> This looks like it's approved, does it still need a review?
Nope! Removed the label

**Comment by dopeters** [comment]
Doc PR https://github.com/nasa/cumulus-distribution-api/pull/4

**Pull request merged**
