### PR TITLE
[CUMULUS-2889] Removes unused CloudWatch Logs client from aws-client

### PR DESCRIPTION
**Pull request by paulpilone**
**Summary:** Summary of changes

Addresses [CUMULUS-2889: Update Cloudwatch Logs code to AWS SDK v3](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2889)

## Changes

* Removes CloudWatch Logs client from aws-client because it's not references anywhere in our code.

## PR Checklist

- [x] Update CHANGELOG
- [x] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Comment by paulpilone** [comment]
This PR targets the https://github.com/nasa/cumulus/tree/pp/task/CUMULUS-2890-cloudwatch-v3 branch because it incorporates some small changes from that branch. If that branch gets merged I can update this PR to point to `master`.

**Comment by paulpilone** [comment]
This PR should replace https://github.com/nasa/cumulus/pull/3545 because the decision was made to remove the client since it's not used.

**Comment by Jkovarik** [comment]
Closing in favor of #3562

**Comment by Jkovarik** [comment]
Closed in favor of #3563

**Pull request closed without merging**
