### PR TITLE
Release 9.2.1

### PR DESCRIPTION
**Pull request by npauzenga**
Edit 7-29: We've updated this PR to point to the original `release-9.2.x` branch. That branch was reset to the v9.2.0 tag so should represent the 9.2 release exactly.

Previous comment: This was a little wonky. The original `release-9.2.x` branch had merges from master _after_ the actual release so I'm not using that here. Instead, I created a new branch called `release-9.2.0-base` from the `v9.2.0` git tag. That's the destination for this PR. 

As a part of this review, it's worth verifying the `release-9.2.0-base` branch. That needs to represent the 9.2 release. It's a new branch so that isn't a given.

To make things even more complicated, the fix here was originally merged to `master` in this PR: https://github.com/nasa/cumulus/pull/2390. So that meant that I needed the cherry-pick the relevant commits from that feature branch into this PR.

### CODE REVIEW

**Comment by npauzenga** [comment]
I think I see why we use the `x` in the minor version base branch. This new minor version branch I created, `release-9.2.0-base`, is going to be mis-named once this is merged. I think I'll need to rename the branch before creating the release tag.

**Comment by npauzenga** [comment]
I suppose this will also need to be backported to 9.3.1. If someone jumps from, say, 9.1 directly to 9.3, they'd miss this change.

**Comment by Jkovarik** [comment]
> I think I see why we use the `x` in the minor version base branch. This new minor version branch I created, `release-9.2.0-base`, is going to be incorrectly named once this is merged. I think I'll need to rename the branch before creating the release tag.

Yeah, we should use the -x on all release branches.   If the docs don't state this we should update them.

**Comment by npauzenga** [comment]
> > I think I see why we use the `x` in the minor version base branch. This new minor version branch I created, `release-9.2.0-base`, is going to be incorrectly named once this is merged. I think I'll need to rename the branch before creating the release tag.
> 
> Yeah, we should use the -x on all release branches. If the docs don't state this we should update them.

Yup. It is documented that way, I don't think we need to update. This target branch is named weirdly because we already have a `release-9.2.x` that I'm _not_ using for this PR (let's talk). I needed a new unique name and this made sense at the time 😄 . 

My hope is that we can replace the original, messed up `release-9.2.x` branch with this new `release-9.2.0-base` and rename `release-9.2.0-base` to `release-9.2.x` but we'll chat.

**Review by flamingbear — APPROVED** [review]
LGTM.

**Pull request merged**
