### PR TITLE
CUMULUS-3798: Creates release v18.3.2

### PR DESCRIPTION
**Pull request by paulpilone**
**Summary:** Summary of changes

Addresses [CUMULUS-3798: Create and publish Release 18.3.2](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3798)

## Changes

* Updates package versions for 18.3.2
* Updates CHANGELOG for 18.3.2
* Moves versioned docs to v18.3.2 based on instructions in the release doc

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Review by npauzenga — CHANGES_REQUESTED** [review]
Looks great @paulpilone. I have a couple questions just for my sanity:
1. Are there any API docs pending for this? `npm run docs-build-packages` doesn't generate anything? Probably all taken care of in the child PRs
2. Do we need a new version of the Cumulus docs? It _feels_ like yes and I don't see it here but that doesn't mean it's not slated for another PR or already done. Just didn't see it here.
3. The tickets I see here are 3700, 3424, 3760, 3742, 3385, NDCUM-1051, 3807, 3787, 3785, 3326. Does that match what we planned?

**Comment by paulpilone** [comment]
> Looks great @paulpilone. I have a couple questions just for my sanity:
> 
> 1. Are there any API docs pending for this? `npm run docs-build-packages` doesn't generate anything? Probably all taken care of in the child PRs

I ran `npm run docs-buid-packages` but that didn't result in any changes.

> 2. Do we need a new version of the Cumulus docs? It _feels_ like yes and I don't see it here but that doesn't mean it's not slated for another PR or already done. Just didn't see it here.

Does "Cumulus docs" == website/versioned_[docs|sidebars]? If so, the changes include moving the 18.3.1 docs to 18.3.2 based on the recommendation in the release.md. The release docs suggest if it's a patch update to just mv the existing docs vs creating a new set. I don't have an opinion here - I was just following the instructions :-).

> 3. The tickets I see here are 3700, 3424, 3760, 3742, 3385, NDCUM-1051, 3807, 3787, 3785, 3326. Does that match what we planned?

That _looks_ right to me but I'll verify that list with Matt and Stefani.

**Comment by npauzenga** [comment]
> > 2. Do we need a new version of the Cumulus docs? It _feels_ like yes and I don't see it here but that doesn't mean it's not slated for another PR or already done. Just didn't see it here.
> 
> Does "Cumulus docs" == website/versioned_[docs|sidebars]? If so, the changes include moving the 18.3.1 docs to 18.3.2 based on the recommendation in the release.md. The release docs suggest if it's a patch update to just mv the existing docs vs creating a new set. I don't have an opinion here - I was just following the instructions :-).

Yeah, sorry, I should specify as we have many different types of "Cumulus docs" 😄. I do mean the website/versioned docs. And yes, I think for a patch version (if we're SemVering correctly) we can just copy it over. Not absolutely critical as we sometimes forget but it's good to avoid confusion.

**Review by npauzenga — APPROVED** [review]
Looks great. Thanks @paulpilone!

**Pull request merged**
