### PR TITLE
CUMULUS-3351: Group CMR online access URLs by link type

### PR DESCRIPTION
**Pull request by colecu**
**Summary:** Group online access URLs so that all HTTP links come first followed by all S3 links, without any other changes in ordering.

Addresses [CUMULUS-3351: Group CMR online access URLs by link type](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3351)

## Changes

* Modified `constructOnlineAccessUrls` in `cmrjs` package to group links by type with no other change in ordering.

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Comment by botanical** [comment]
@colecu thanks for the contribution! This will be reviewed soon. Quick question - what is the reason why this PR is pointing towards release 15?

**Comment by colecu** [comment]
@botanical Thanks! The PR was generated from the branch we were deploying at the time in order to address an NSIDC ticket, which happed to be release 15. There was no other reason for doing so; we are on release 16 now. In the future would you prefer that we push to master on our fork before submitting a PR?

**Comment by botanical** [comment]
> @botanical Thanks! The PR was generated from the branch we were deploying at the time in order to address an NSIDC ticket, which happed to be release 15. There was no other reason for doing so; we are on release 16 now. In the future would you prefer that we push to master on our fork before submitting a PR?

@colecu Ah, great. Thanks for the context. And yeah, pointing your forked PR to master would be our preference!

**Comment by botanical** [comment]
@colecu do you mind adding a unit test for your changes?

**Comment by colecu** [comment]
@botanical I don't mind adding a unit test. I have a couple tickets I need to get closed out, but as soon as that is done I will work on adding the test. Thanks for the review.

**Comment by colecu** [comment]
@botanical I have a unit test ready. Would you like me to update the PR to point to a branch that is directly tracking master in order to get rid of any issues with it originally being created from v15? I did the unit test work on a branch created from master on our fork, so it isn't really any extra effort if it would simplify things for you.

**Comment by botanical** [comment]
> @botanical I have a unit test ready. Would you like me to update the PR to point to a branch that is directly tracking master in order to get rid of any issues with it originally being created from v15? I did the unit test work on a branch created from master on our fork, so it isn't really any extra effort if it would simplify things for you.

Yeah, if you could update the PR to point to a branch that is directly tracking the main branch `master`, that would be great. Thank you!

**Comment by colecu** [comment]
@botanical I have created a new PR (#3479) to replace this one, which has the unit test and is created against master. This one can be closed if you are good with that. If you would prefer I do this in some other way, please let me know. Apologies for complicating things with the non-master PR.

**Comment by botanical** [comment]
> @botanical I have created a new PR (#3479) to replace this one, which has the unit test and is created against master. This one can be closed if you are good with that. If you would prefer I do this in some other way, please let me know. Apologies for complicating things with the non-master PR.

@colecu thanks so much! I've reviewed your PR and the changes look solid 🙇 I've opened a PR to add changelog notes https://github.com/nasa/cumulus/pull/3480. Hopefully these changes will be reviewed by the Cumulus Core team and merged soon. Please feel free to close this PR.

**Comment by botanical** [comment]
https://github.com/nasa/cumulus/pull/3480 @colecu this work has been merged into core. Thank you again for your contribution!

**Pull request closed without merging**
