### PR TITLE
Add names to all security groups

### PR DESCRIPTION
**Pull request by reweeden**
**Summary:**
If you don't give security groups a name, terraform will generate one automatically based on the time e.g. `terraform-20210730180207019300000001`. When you have several of these in the same account it becomes impossible to tell which terraform resource they belong to. This problem becomes even worse when you have 12 cumulus stacks deployed each with 5 unnamed security groups as we do in our sandbox account.

## Changes

* Added `name` attribute for all security groups that didn't have one
* Replaced `name_prefix` with `name` for the few groups that were using `name_prefix`. I did this just for consistency. This is in it's own commit so it can easily be reverted if not desired.

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Comment by Jkovarik** [comment]
hi @reweeden  

Thanks again for the contribution - and apologies it took this long to get back to it.   I've opened up CUMULUS-2999 in support of the evaluation. 

I took a look at the update, and the PR itself is sound, however for existing deployments this update would force replacement of SGs like the elasticsearch group, which in loaded production deployments might result in database write failures and/or other deployment complications if the security group still has things like attached interfaces assigned to it, etc. 

Having these be named is a *wonderful* idea, however I think we need to spend time to evaluate if we can make that change and reasonably support user migration efforts.     I'm going to discuss this in our internal architecture meeting and get back to you.  

In the meantime I'm wondering if a tag-based approach might get you what you need without incurring the operational support costs I'm concerned about above?

**Comment by reweeden** [comment]
Thanks for taking a look at this. I believe the security groups are already tagged so it is possible to distinguish them that way, but it's not always as convenient as looking at the name because it depends on whether or not the tags are displayed in the console or returned by the AWS API which can vary depending on what you're doing. The group name is always displayed or included in the response.

**Comment by botanical** [comment]
Hi @reweeden, I've picked up this PR to review and tried deploying the changeset to my sandbox Cumulus deployment. The deployment didn't succeed and I ran into errors such as :
```
Error: Error deleting security group: DependencyViolation: resource sg-******* has a dependent object
```
and

```
Error: error deleting Lambda ENIs using Security Group (sg-*********): error waiting for Lambda ENI (eni-**********) to become available for detachment: timeout while waiting for state to become 'available' (last state: 'in-use', timeout: 45m0s)
```

While helpful in distinguishing ownership of resources, I think the changes you suggest would have non-trivial implications for already-deployed Cumulus stacks since renaming security groups requires deleting and creating new security groups. At this time, I think we can't accept the changes you propose in this PR. What are your thoughts, @reweeden?

**Comment by reweeden** [comment]
OK. That's too bad. It would be helpful if any new security groups that get added in the future would have names.

**Comment by botanical** [comment]
> OK. That's too bad. It would be helpful if any new security groups that get added in the future would have names.

That is definitely a reasonable ask and I have created an architecture decision log to note that all future security groups should be named https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=266962745. I'm going to close this PR. Thanks so much for your contribution and discussion @reweeden!

**Pull request closed without merging**
