### PR TITLE
CUMULUS-3931: Allowing force_new_deployment to be configurable for ecs services.

### PR DESCRIPTION
**Pull request by Jkovarik**
**Summary:** Summary of changes

Addresses [CUMULUS-3931](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3931)

## Changes

- Adds `force_new_deployment` configuration to the ecs_service to force redeploy on update

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Comment by Jkovarik** [comment]
Bringing in #3835

**Comment by Jkovarik** [comment]
Added changelog, up for review.   Thanks @Michaellh0079 for the contrib! 🎉

**Review by npauzenga — APPROVED** [review]
Looks good. I can't see a reason not to provide this. I don't think there's much value in including it in the example deployment either so 👍

**Comment by Jkovarik** [comment]
@Michaellh0079 this has been merged and will go out with the next forward release.   Thanks again.

**Pull request merged**
