### PR TITLE
Jk/cumulus 3210

### PR DESCRIPTION
**Pull request by Jkovarik**
**Summary:** Summary of changes

Addresses [CUMULUS-3210: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3120)

## Changes

* Fixes TF configuration bug documented in CUMULUS-3210

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [x] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

Marking low priority *only* because team prioritization hasn't been set.

### CODE REVIEW

**Comment by Jkovarik** [comment]
I validated this while doing other testing, with the variable added to the example project cumulus_distribution and archive modules set what appear to be the correct retention periods, this should resolve the ticket.

**Comment by mikedorfman** [comment]
This looks great and tackles the main part of CUMULUS-3120.  I'm not sure if this belongs in the same PR, but I also noticed `default_log_retention_days` isn't exposed to the Cumulus module - it's just defined in the  submodules but not overridden by the cumulus module.  Any way this small change can go in here too?  The changes that would be involved:
 - Update to cumulus/variables.tf with default_log_retention_days (identical to the var defined in archive, ingest, etc).
 - Update to cumulus/archive.tf, cumulus/ingest.tf, cumulus/distribution.tf to pass this variable through to these submodules.

**Comment by mikedorfman** [comment]
Ah, nitpick, but the ticket I created is CUMULUS-3210 (branch name and description above show CUMULUS-3120).

**Comment by Jkovarik** [comment]
Correct you are @mikedorfman , thanks for pointing it out.    I've updated the ticket description (the branch name looks right).

**Comment by Jkovarik** [comment]
I'll continue to update this, but it's going to need review prioritization re: CUMULUS-3210 for team review work.

**Comment by mikedorfman** [comment]
@Jkovarik - sorry for the delayed notification, but it looks like these changes may have been duplicated as part of https://github.com/nasa/cumulus/pull/3346

**Pull request closed without merging**
