### PR TITLE
CUMULUS-2000: queue multiple granules (needs review)

### PR DESCRIPTION
**Pull request by nemreid**
**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Updated `@cumulus/queue-granules` to respect a new config parameter: `preferredQueueBatchSize`. Queue-granules will respect this batchsize as best as it can to batch granules into workflow payloads. As workflows generally rely on information such as collection and provider expected to be shared across all granules in a workflow, queue-granules will break batches up by collection, as well as provider if there is a `provider` field on the granule. This may result in batches that are smaller than the preferred size, but never larger ones. The default value is 1, which preserves current behavior of queueing 1 granule per workflow.

## PR Checklist

- [x] Update CHANGELOG
- [x] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Review by laurenfrederick — COMMENTED** [review]
@nemreid I tested this and it looks very cool. I am confused in the CHANGELOG, how do we get granules with different collections and/or providers? Since the rule is run for a particular collection and provider and that's in the meta, how would we get into a situation where they would be different for a batch of granules?

**Comment by nemreid** [comment]
@laurenfrederick Since queue-granules follows both DiscoverGranules and ParsePdr, the PDR use case is be one where we could have a PDR containing multiple granules with different providers/hosts/collections.

**Comment by nemreid** [comment]
I have not put in an integration test case for the PDR use case, I'm open to adding one if you think it adds value.

**Comment by laurenfrederick** [comment]
Do you have PDR we can use to test it?? I haven't even tested that scenario and that is what I am worried about. I guess I should try testing the PDR case even with the same collection.

**Comment by nemreid** [comment]
We do have `multi-data-type.PDR` to test multiple collections, but we don't have one with multiple different `NODE_NAME`s. However, I think I can set one up for a spec test.

**Comment by Jkovarik** [comment]
https://github.com/nasa/cumulus/pull/2453 is up for CI, when this passes PR we'll need to approve that one for the merge.

**Comment by nemreid** [comment]
merged in via https://github.com/nasa/cumulus/pull/2453

**Pull request closed without merging**
