### PR TITLE
CUMULUS-3608: Adds variable for sqs message consumer watcher message and time limits

### PR DESCRIPTION
**Pull request by paulpilone**
**Summary:** Summary of changes

Addresses [CUMULUS-3608: Make sqs_message_consumer_watcher messageLimit configurable](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3608)

## Changes

* Exposes message and time limit Terraform vars for sqs_message_consumer_watcher Lambda

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Comment by paulpilone** [comment]
I reviewed the sqs message consumer watcher Lambda code and didn't find anything obvious that should stop users from being able to configure these values. At most it would increase calls to S3; however, S3 actions are small potatoes when compared to the workflows this function ultimately kicks off.

I exposed both variables because it makes sense if you're going to increase the message limit you might also want to increase the timeout.

**Comment by paulpilone** [comment]
Note of concern: exposing the timeout could result in the user setting that to a value greater than the actual Lambda timeout. I suppose this is something we should provide guidance on or else not expose the timeout at all.

**Review by npauzenga — CHANGES_REQUESTED** [review]
This looks great @paulpilone. I think you're right and the trick here is guidance. We should probably have some rough idea of what numbers are safe or how to evaluate that. Also a note about the Lambda timeout to your earlier point would probably make sense.

**Review by npauzenga — APPROVED** [review]
Looks great @paulpilone! Thanks for adding details to the new params. I think we can leave it there and explicitly tell DAACs that are interested where to look.

**Pull request merged**
