### PR TITLE
merge release-12.0.3 changelog to master

### PR DESCRIPTION
**Pull request by charleshuang80**
**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Review by npauzenga — CHANGES_REQUESTED** [review]
Looks good except one thing: at the bottom of the changelog there's an index of all the versions with links to the diff between the current version and the previous. I think we need one here. e.g. https://github.com/nasa/cumulus/pull/3116/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR6543-R6544

**Comment by charleshuang80** [comment]
> Looks good except one thing: at the bottom of the changelog there's an index of all the versions with links to the diff between the current version and the previous. I think we need one here. e.g. https://github.com/nasa/cumulus/pull/3116/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR6543-R6544

added

**Review by npauzenga — APPROVED** [review]
Nice work getting this through @charleshuang80!

**Comment by charleshuang80** [comment]
Thanks. And thanks for all your help!

**Pull request merged**
