### PR TITLE
Release 9.4.0

### PR DESCRIPTION
**Pull request by jaortega527**
**Summary:** Release 9.3.0

## PR Checklist

- [x] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Review by jennyhliu — APPROVED** [review]
LGTM👍

**Comment by jennyhliu** [comment]
You need to add release doc.
https://github.com/nasa/cumulus/releases/tag/v9.4.0

**Comment by jennyhliu** [comment]
Noticed that [Mark's PR]( https://github.com/nasa/cumulus/pull/2412) was not included in your release, and need to move the CHANGLOG.md entry to `Unreleased`.

**Review by jennyhliu — CHANGES_REQUESTED** [review]
please update CHANGLOG.md

**Comment by markdboyd** [comment]
@jennyhliu My PR (#2412) was merged after the release process was started, so it shouldn't be included in the release

**Comment by jaortega527** [comment]
Thanks for catching that. I missed it when merging master into the 9.4.x-merge... branch. I'll get it fixed now.

**Comment by jaortega527** [comment]
@jennyhliu CHANGELOG.md has been updated to reflect that PR #2412 is not included in the 9.4.0 release. Thank you again for catching that..

**Comment by jaortega527** [comment]
Release doc has also been updated [Updated release doc](https://github.com/nasa/cumulus/releases/tag/v9.4.0)

**Review by jennyhliu — APPROVED** [review]

**Pull request merged**
