### PR TITLE
Release 19.1.0

### PR DESCRIPTION
**Pull request by npauzenga**
Minor version merge including version bump, docs, website.

### CODE REVIEW

**Comment by npauzenga** [comment]
Temporarily moving to WIP. We need the CL updates from the 18.5.0 release in main. Once merged we can update this release.

**Comment by npauzenga** [comment]
Ok, this is updated with the CL merge from 18.5.0 and should be current. Definitely worth triple-checking. Note that main had a merge or two since the original PR here was opened.

**Comment by paulpilone** [comment]
@npauzenga This looks good to me other than:

1. Waiting on orca to respond.
2. Needs to pull in 18.5.0 website docs: https://github.com/nasa/cumulus/pull/3819

**Review by paulpilone — CHANGES_REQUESTED** [review]
@npauzenga This looks good to me other than:

Waiting on orca to respond.
Needs to pull in 18.5.0 website docs: https://github.com/nasa/cumulus/pull/3819

**Comment by npauzenga** [comment]
PR is up-to-date with the 18.5 docs and latest from main (as this is a forward release). Temporarily blocking further review/merging until we sort the Orca version. Details in the Jira ticket. https://bugs.earthdata.nasa.gov/browse/CUMULUS-3898

**Comment by npauzenga** [comment]
This is updated with the latest from main and includes the new Orca v10.0.1 release.

**Comment by npauzenga** [comment]
Also need the cumulus template review: https://github.com/nasa/cumulus-template-deploy/pull/92/files

**Review by paulpilone — APPROVED** [review]

**Pull request merged**
