### PR TITLE
Add ISO support to move-granules task

### PR DESCRIPTION
**Pull request by michaeljb**
**Summary:** Summary of changes

## Changes

add `filterFunc` parameter to `granulesToCmrFileObjects`, add new func `isISOFile`

rename some functions:

* `isECHO10File` -> `isECHO10Filename`
* `isUMMGFile` -> `isUMMGFilename`
* `isISOFile` -> `isCMRISOFilename`

add new functions:

* `isISOFilename` - checks if filename ends with `.iso.xml` extension
* `isISOFile` - checks if file object's filename matches the "ISO" or "CMRISO" pattern

allow `metadataObjectFromCMRFile` to open .iso.xml files

Addresses [NDCUM-624](https://bugs.earthdata.nasa.gov/browse/NDCUM-624) for NSIDC

Co-authored-by: Mark Schwab <schwabm@nsidc.org>

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

### CODE REVIEW

**Comment by Jkovarik** [comment]
@michaeljb  I'll get started on the high-level review, however it looks like there are some conflicts from recent merges, would you mind doing an update/merge?

**Comment by michaeljb** [comment]
@Jkovarik thanks for the heads-up, will work on rebasing presently...

**Review by Jkovarik — APPROVED** [review]
Approving for internal team review.

**Comment by Jkovarik** [comment]
Closing in favor of https://github.com/nasa/cumulus/pull/2549

**Pull request closed without merging**
