### PR TITLE
CUMULUS-2033: Move state machine definitions to *.asl.json files

### PR DESCRIPTION
**Pull request by markdboyd**
**Summary:** Summary of changes

Addresses [CUMULUS-2033: CUMULUS-2033: Move state machine definitions to *.asl.json files](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2033)

I confirmed that deploying with these file changes results in 0 applied changes to the deployed workflows

## Changes

* Moved state machine definitions to *.asl.json files

### CODE REVIEW

**Comment by Jkovarik** [comment]
> Finally, as a separate PR, do we need to update the template repo?

Just a guess, but that probably requires a separate *ticket*.  I don't know that the Right Thing(tm) was done on the last deployment, given the last updates to this were *4 months* ago. 

I don't think we should hold up this ticket on that particularly.

**Comment by Jkovarik** [comment]
>Do we also want to update the examples in the following files?
>
>docs/data-cookbooks/cnm-workflow.md
>docs/data-cookbooks/run-tasks-in-lambda-or-docker.md
>docs/workflows/developing-a-cumulus-workflow.md
>tf-modules/workflow/README.md

Mixed feelings here -- splitting it in-line might be confusing to users unfamiliar with TF generally, but good for them in setting a better pattern.    I suppose some descriptive text explaining 'two files' *if* we did the example template updates would work.     I could go either way.

**Comment by markdboyd** [comment]
@Jkovarik @chuckwondo How do we feel about leaving the documentation examples as is without showing the use of the separate .asl.json files? The documentation is just showing you how to get a workflow deployed and using the separate JSON files isn't required for that. Plus I feel like trying to explain the use of two files might be less clear.

At the same time, I would like to update the template repo to use .asl.json files as a demonstration to our users that it is possible. So then users would have a demo to follow if they want.

**Comment by chuckwondo** [comment]
> @Jkovarik @chuckwondo How do we feel about leaving the documentation examples as is without showing the use of the separate .asl.json files? The documentation is just showing you how to get a workflow deployed and using the separate JSON files isn't required for that. Plus I feel like trying to explain the use of two files might be less clear.
> 
> At the same time, I would like to update the template repo to use .asl.json files as a demonstration to our users that it is possible. So then users would have a demo to follow if they want.

Works for me.

**Comment by Jkovarik** [comment]
> @Jkovarik @chuckwondo How do we feel about leaving the documentation examples as is without showing  the use of the separate .asl.json files? The documentation is just showing you how to get a workflow deployed and using the separate JSON files isn't required for that. Plus I feel like trying to explain the use of two files might be less clear.

Works for me!

**Pull request merged**
